import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import ResourceList from "@/components/education/ResourceList";
import SustainabilityTip from "@/components/education/SustainabilityTip";
import { CategoryIcon } from "@/components/ui/category-icon";

export default function Learn() {
  const [activeCategory, setActiveCategory] = useState<number | null>(null);
  
  // Fetch categories
  const { data: categories, isLoading: isLoadingCategories } = useQuery({
    queryKey: ["/api/categories"],
    queryFn: async () => {
      const res = await fetch("/api/categories");
      if (!res.ok) throw new Error("Failed to fetch categories");
      return res.json();
    }
  });

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-8">
        <h2 className="text-2xl font-bold text-neutral-800">
          Sustainability Learning Hub
        </h2>
        <p className="text-neutral-600 mt-1">
          Expand your knowledge about sustainability and environmental impact
        </p>
      </div>
      
      {/* Featured Educational Content */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-12">
        <Card className="lg:col-span-2">
          <CardContent className="p-6">
            <div className="aspect-w-16 aspect-h-9 mb-4 bg-neutral-100 rounded-lg overflow-hidden">
              <img 
                src="https://images.unsplash.com/photo-1592834454854-69b40fa0b6f9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" 
                alt="Sustainability concept"
                className="object-cover w-full h-full"
              />
            </div>
            
            <h3 className="text-xl font-bold text-neutral-800 mb-2">
              Understanding Your Carbon Footprint
            </h3>
            
            <p className="text-neutral-600">
              Your carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) 
              that are generated by your actions. The average carbon footprint for a person in the United States is 
              16 tons, one of the highest rates in the world. Globally, the average carbon footprint is closer to 4 tons.
            </p>
            
            <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="bg-neutral-50 p-4 rounded-lg">
                <h4 className="font-bold text-neutral-800 mb-2">Direct Emissions</h4>
                <p className="text-sm text-neutral-600">
                  These come from sources that are directly owned or controlled by you, like your car's exhaust 
                  or your home's heating system.
                </p>
              </div>
              
              <div className="bg-neutral-50 p-4 rounded-lg">
                <h4 className="font-bold text-neutral-800 mb-2">Indirect Emissions</h4>
                <p className="text-sm text-neutral-600">
                  These result from your activities but come from sources you don't directly control, 
                  like the electricity you use or the manufacturing of products you buy.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
        
        <div>
          <SustainabilityTip />
        </div>
      </div>
      
      {/* Category-based Resources */}
      <div className="mb-8">
        <h3 className="text-xl font-bold text-neutral-800 mb-4">
          Explore by Category
        </h3>
        
        <Tabs 
          defaultValue="all" 
          value={activeCategory === null ? "all" : activeCategory.toString()}
          onValueChange={(value) => setActiveCategory(value === "all" ? null : Number(value))}
        >
          <TabsList className="mb-6 flex w-full overflow-x-auto pb-1">
            <TabsTrigger value="all" className="flex-shrink-0">
              All Categories
            </TabsTrigger>
            
            {isLoadingCategories ? (
              <div className="flex space-x-2">
                {[1, 2, 3, 4].map((i) => (
                  <div key={i} className="h-10 w-24 bg-neutral-200 rounded animate-pulse"></div>
                ))}
              </div>
            ) : (
              categories?.map((category: any) => (
                <TabsTrigger 
                  key={category.id} 
                  value={category.id.toString()}
                  className="flex-shrink-0"
                >
                  <CategoryIcon 
                    category={category.name}
                    size={16}
                    className="mr-2"
                    color={category.color}
                  />
                  {category.name}
                </TabsTrigger>
              ))
            )}
          </TabsList>
          
          <TabsContent value="all">
            <ResourceList showTabs={true} />
          </TabsContent>
          
          {!isLoadingCategories && categories?.map((category: any) => (
            <TabsContent key={category.id} value={category.id.toString()}>
              <ResourceList categoryId={category.id} showTabs={true} />
            </TabsContent>
          ))}
        </Tabs>
      </div>
      
      {/* Educational Infographic */}
      <div className="bg-primary bg-opacity-5 rounded-xl p-6 mb-8">
        <h3 className="text-xl font-bold text-primary mb-4">
          The Path to Carbon Neutrality
        </h3>
        
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 text-center">
          <div className="flex flex-col items-center">
            <div className="h-16 w-16 rounded-full bg-primary bg-opacity-20 text-primary flex items-center justify-center mb-3">
              <span className="text-2xl font-bold">1</span>
            </div>
            <h4 className="font-bold text-neutral-800 mb-1">Measure</h4>
            <p className="text-sm text-neutral-600">
              Calculate your carbon footprint to understand your impact
            </p>
          </div>
          
          <div className="flex flex-col items-center">
            <div className="h-16 w-16 rounded-full bg-primary bg-opacity-20 text-primary flex items-center justify-center mb-3">
              <span className="text-2xl font-bold">2</span>
            </div>
            <h4 className="font-bold text-neutral-800 mb-1">Reduce</h4>
            <p className="text-sm text-neutral-600">
              Take steps to lower your emissions where possible
            </p>
          </div>
          
          <div className="flex flex-col items-center">
            <div className="h-16 w-16 rounded-full bg-primary bg-opacity-20 text-primary flex items-center justify-center mb-3">
              <span className="text-2xl font-bold">3</span>
            </div>
            <h4 className="font-bold text-neutral-800 mb-1">Offset</h4>
            <p className="text-sm text-neutral-600">
              Balance remaining emissions with carbon offset projects
            </p>
          </div>
          
          <div className="flex flex-col items-center">
            <div className="h-16 w-16 rounded-full bg-primary bg-opacity-20 text-primary flex items-center justify-center mb-3">
              <span className="text-2xl font-bold">4</span>
            </div>
            <h4 className="font-bold text-neutral-800 mb-1">Advocate</h4>
            <p className="text-sm text-neutral-600">
              Share your journey and inspire others to take action
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
